#!/usr/bin/env php
<?php

/**
 * WebPlatform MediaWiki Conversion.
 **/

require_once __DIR__ . '/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$console = new Application();
require_once __DIR__ . '/../lib/loader.php';
$console->run();
